#! /bin/bash

ancestor_file=$1
current_file=$2
local_file=$3
merge_file=$4

exec /Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n -e
   "(ediff-3-way-merge \"$2\" \"$3\" \"$1\" nil \"$1\" )"







