#! /bin/bash

file=$1
message=$2

# -kb  : is so it doesn't do header mutilation
# -U   : disable strict locking
# -u   : remove lock
# -T   : preserve modification time

echo <<EOF | rcs -kb -u -U -T "$1"
description.
$2
.

EOF
